url: http://kaa7.github.io/

# Site settings
title: Holidaze
email: antonio.carapcea@gmail.com
description: "Holidaze"


# Team names, titles and social links
people:
- name: Andrei-Antonio Carapcea
  pic: 0
  position: Product Owner
  email: antonio.carapcea@gmail.com
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/carapcea-andrei-antonio/
- name: Bianca-Ana-Maria Rusu
  pic: 1
  position: Project Manager
  email: bianca.am.rusu@gmail.com
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/vladcatanoiu/
- name: Alexandru Careja
  pic: 2
  position: Full Stack Developer
  email: careja.alexandru@gmail.com
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/alexcareja
- name: Gloria Popa
  pic: 3
  position: Full Stack Developer
  email: gloria.popa16@gmail.com
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/gloria-popa/
- name: Eduard Olteanu
  pic: 4
  position: Full Stack Developer
  email: edi.olteanu@gmail.com
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/edi-olteanu
- name: Elena Damian
  pic: 5
  position: Full Stack Developer
  email: damian.elena75@gmail.com
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/edamian
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: instagram
  #   url: #
  - title: github
    url: https://github.com/ArtistryHub/ArtistryHub

# Postal address (add as many lines as necessary)
address:
  - line: ACS, UPB
  - line: Bucharest, Romania

# Build settings
markdown: kramdown
permalink: pretty